datasets:
  raw:
    FnB:
      google_search_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/raw/google_search_data.csv
        driver_params: {}
      product_manufacturer_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
        driver_params: {}
      sales_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/raw/sales_data.csv
        driver_params: {}
      social_media_data:
        type: ds
        format: xlsx
        uri: ${core.data_base_path}/raw/social_media_data.xlsx
        driver_params: {}
      theme_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/raw/theme_list.csv
        driver_params: {}
      theme_product_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/raw/theme_product_list.csv
        driver_params: {}
  
  cleaned:
    FnB:
      google_search_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/google_search_data.csv
        driver_params: {}
      product_manufacturer_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/product_manufacturer_list.csv
        driver_params: {}
      sales_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/sales_data.csv
        driver_params: {}
      social_media_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/social_media_data.csv
        driver_params: {}
      theme_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/theme_list.csv
        driver_params: {}
      theme_product_list:
        type: ds
        format: csv
        uri: ${core.data_base_path}/cleaned/theme_product_list.csv
        driver_params: {}

  train:
    FnB:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/train/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/train/target.csv
        driver_params:
          save:
            index: False
  test:
    FnB:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/target.csv
        driver_params:
          save:
            index: False

  processed:
    FnB:
      client_data:
        type: ds
        format: csv
        uri: ${core.data_base_path}/processed/client_data.csv
        driver_params: {}

  score:
    FnB:
      output:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/output.csv
        driver_params:
          save:
            index: False